# Changes in master
# Run on all platforms latest versions
jobs:
  - template: latest-version.yml
    parameters:
        name: Linux_master
        vmImage: 'ubuntu-latest'
        condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), not(eq(variables['Build.Reason'], 'Schedule')))
        worker: 'standard.yml'

  - template: latest-version.yml
    parameters:
        name: macOS_master
        vmImage: 'macOS-latest'
        condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), not(eq(variables['Build.Reason'], 'Schedule')))
        worker: 'standard.yml'

  - template: latest-version.yml
    parameters:
        name: Windows_master
        vmImage: 'windows-latest'
        condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), not(eq(variables['Build.Reason'], 'Schedule')))
        worker: 'standard.yml'
